export const Theme = {
  colors: {
    primary: "var(--color-primary)",
    primaryDark: "var(--color-primary-dark)",
    accent: "var(--color-accent)",
    success: "var(--color-success)",
    danger: "var(--color-danger)",
    warning: "var(--color-warning)",
    background: "var(--color-background)",
    backgroundSecondary: "var(--color-background-secondary)",
    surface: "var(--color-surface)",
    surfaceMuted: "var(--color-surface-muted)",
    text: "var(--color-text)",
    textSecondary: "var(--color-text-secondary)",
    textMuted: "var(--color-text-muted)",
    textOnPrimary: "var(--color-text-on-primary)",
    border: "var(--color-border)",
    borderStrong: "var(--color-border-strong)",
    overlay: "var(--color-overlay)",
    shadow: "var(--color-shadow)",
  },
  radius: {
    sm: "var(--radius-sm)",
    md: "var(--radius-md)",
    lg: "var(--radius-lg)",
    xl: "var(--radius-xl)",
    pill: "var(--radius-pill)",
  },
  spacing: {
    xs: "var(--spacing-xs)",
    sm: "var(--spacing-sm)",
    md: "var(--spacing-md)",
    lg: "var(--spacing-lg)",
    xl: "var(--spacing-xl)",
    xxl: "var(--spacing-xxl)",
  },
};